name: Check Copyright Year

on:
  push:
  pull_request:

jobs:
  check-year:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Check copyright year
        run: |
          current_year=$(date +'%Y')
          copyright_year=$(grep -oP '(?<=# Copyright \(c\) )\d{4}' src/main.py || echo "0")
          if [ "$current_year" -ne "$copyright_year" ]; then
            echo "Copyright year in main.py ($copyright_year) does not match current year ($current_year)."
            exit 1
          else
            echo "Copyright year is correct."
          fi