name: Check Copyright Year

permissions:
  contents: write
  
on:
  push:
  pull_request:

jobs:
  check-year:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update copyright year in modified files
        run: |
          set -e
          current_year=$(date +'%Y')
          # Try to get modified files, fallback to all tracked files if this is the first commit
          if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
            MODIFIED_FILES=$(git diff --name-only HEAD~1)
          else
            MODIFIED_FILES=$(git ls-files)
          fi
          for file in $MODIFIED_FILES; do
            if grep -qE '# Copyright \(c\) [0-9]{4}' "$file"; then
              echo "Updating copyright year in $file"
              sed -i "s/# Copyright (c) [0-9]\{4\}/# Copyright (c) $current_year/" "$file"
            fi
          done
          # Show changes
          git diff
      
      - name: Commit and push changes if needed
        env:
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if ! git diff --quiet; then
            git add .
            git commit -m "chore: update copyright year to $(date +'%Y')"
            git push
          else
            echo "No changes to commit."
          fi