name: Check Copyright Year

on:
  push:
  pull_request:

jobs:
  check-year:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update copyright year in modified files
        run: |
          current_year=$(date +'%Y')
          # Get list of modified files in the push/PR
          git fetch origin ${{ github.base_ref }} --depth=1 || true
          MODIFIED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }} || git diff --name-only HEAD~1)
          for file in $MODIFIED_FILES; do
            if grep -qE '# Copyright \(c\) [0-9]{4}' "$file"; then
              echo "Updating copyright year in $file"
              sed -i "s/# Copyright (c) [0-9]\{4\}/# Copyright (c) $current_year/" "$file"
            fi
          done
          # Show changes
          git diff